FROM php:8.1


RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip



RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd


WORKDIR /app
COPY . /app

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

#RUN composer install

EXPOSE 8000
CMD php artisan serve --host=0.0.0.0 --port=8000